# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python

on:
  push:
    branches: main
  pull_request:

permissions: {}

# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]

    steps:
    # on Windows, make sure line-endings are consistent for test suite
    - if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install gettext for translation testing (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get install gettext

    - name: Install gettext for translation testing (macOS)
      if: runner.os == 'macOS'
      run: brew install gettext

    - name: Install gettext for translation testing (Windows)
      if: runner.os == 'Windows'
      run: |
        LATEST_URL=$(curl -s "https://api.github.com/repos/mlocati/gettext-iconv-windows/releases/latest" |
          grep -o 'https://github.com/mlocati/gettext-iconv-windows/releases/download/[^"]*-shared-64\.zip')
        curl -L "$LATEST_URL" -o "$RUNNER_TEMP/gettext.zip"
        unzip "$RUNNER_TEMP/gettext.zip" -d "$RUNNER_TEMP/gettext"
        echo "$RUNNER_TEMP/gettext/bin" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@f8ce4d55b131f4a1e373b8747ca6b6a54133ae5a  # v1.18.0

    - name: Install cargo-llvm-cov
      run: cargo binstall cargo-llvm-cov

    - name: Install Django Rusty Templates
      run: |
        cargo llvm-cov show-env --sh > llvm-cov-env.sh
        source llvm-cov-env.sh
        uv run maturin develop

    - name: Build translation files
      run: |
        uv run -m django compilemessages

    - name: Test with pytest
      run: |
        cargo llvm-cov show-env --sh > llvm-cov-env.sh
        source llvm-cov-env.sh
        uv run pytest --cov --cov-report=xml

    - name: Get rust coverage report
      run: |
        cargo llvm-cov show-env --sh > llvm-cov-env.sh
        source llvm-cov-env.sh
        cargo llvm-cov report -p dtl-lexer -p django-rusty-templates --codecov --output-path codecov.json

    - name: Upload to codecov
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        files: coverage.xml,codecov.json
        fail_ci_if_error: true

  django-test-suite:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      pull-requests: write
      contents: read
    steps:
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

    - name: Checkout main
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: main
        persist-credentials: false

    - name: Run Django test suite (main)
      run: uv run scripts/run_django_test_suite.py --parsed-output main_test_output

    - name: Checkout current branch
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        clean: false
        persist-credentials: false

    - name: Re-build django-rusty-templates (current branch)
      run: uv run maturin develop

    - name: Run Django test suite (current branch)
      run: uv run scripts/run_django_test_suite.py --parsed-output branch_test_output

    - name: Compare test suites & generate comment
      id: generate-comment
      run: |
        echo '<!-- generated-comment ecosystem -->' >> test-diff-result
        echo "### Django test suite conformance" >> test-diff-result

        diff --unified main_test_output branch_test_output >> diff_result || true
        if [ "$(cat diff_result | wc -l)" -gt 0 ]; then
          {
            echo "<details><summary>"
            echo "ℹ️ Test pass rate changed from <code>$(cat diff_result | grep "^-" | grep -oP '\d+\.\d+%')</code> to <code>$(cat diff_result | grep "^+" | grep -oP '\d+\.\d+%')</code>."
            echo "</summary>"
            printf '\n```diff\n'
            cat diff_result
            printf '```\n'
            echo "</details>"
          } >> test-diff-result
        else
          {
            echo "✅ no changes detected running Django test suite."
            printf '\n```diff\n'
            head -n2 branch_test_output
            printf '```\n'
          } >> test-diff-result
        fi
        cat test-diff-result > "$GITHUB_STEP_SUMMARY"
        cat test-diff-result

    - name: Upload test diff result
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-diff-result
        path: test-diff-result

    - name: Store pr-number
      run: |
        echo ${{ github.event.number }} > pr-number

    - name: Upload pr-number
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: pr-number
        path: pr-number
