name: Rust

on:
  push:
    branches: main
  pull_request:

permissions: {}

env:
  CARGO_TERM_COLOR: always
  PYTHONPATH: ${{ github.workspace }}

# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
    - name: Install dependencies
      run: uv sync
      env:
        UV_PROJECT_ENVIRONMENT: ${{ env.pythonLocation }}
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@1800853f2578f8c34492ec76154caef8e163fbca  # v1.17.7
    - name: Install cargo-llvm-cov
      run: cargo binstall cargo-llvm-cov
    - name: Run tests
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      with:
        files: lcov.info
        fail_ci_if_error: true
